
version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: inbox
      POSTGRES_PASSWORD: inboxpassword
      POSTGRES_DB: inboxdb
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
